import scala.io.Source
import org.json4s._
import java.io._

import com.giovanna._

//import org.json4s.native.JsonMethods._
//import scala.collection.mutable.ArrayBuffer
//import com.github.nscala_time.time.Imports._
//import org.json4s.JsonAST.JValue

/** --------------------------  Summary of the program steps ---------------------------------------------------
  *
  * 1. Validate input and output file names parameters
  *   a. Validate input and output file names were given when running the program (these are given in run.sh script)
  *   b. Validate input file exists. (Outputfile existence is not validated as it will be generated by the program)
  *
  * 2. Validate input data is in JSON format and no information is missing
  *
  * 3. Read transaction line from input File. Create Venmo Graph Class, call its "processTransaction" method (pass transaction line as parameter)
  *
  */



/** ----------------------------------------------------------------------------- */
/**                      App Main object with main method                         */
/** ----------------------------------------------------------------------------- */
object VenmoPayments {

  def main(args: Array[String]): Unit = {

    /** ----------------------------------------------- */
    /** Validate input and output file names parameters */
    /** ----------------------------------------------- */

    /** Capture parameters for input and output files. Example of input and output:  */
    //inputFileName = "../venmo_input/venmo-trans.txt"  -- outputFileName = "../venmo_output/output.txt"
    var inputFileName = ""
    var outputFileName = ""

    if (args.length <= 0) {
      println("----------------------------")
      println("MISSING PARAMETERS - Please provide Input and Output file names as parameters")
      println("----------------------------")
      return
    }

    if (args.length == 1) {
      println("----------------------------")
      println("MISSING PARAMETER - Please provide second parameter as the Output file name")
      println("----------------------------")
      return
    }

    if (args.length >= 2) {

      inputFileName = args(0)
      outputFileName = args(1)

      if (!new java.io.File(inputFileName).exists) {

        println("----------------------------")
        println("MISSING INPUT FILE - Input File '" + inputFileName + "' was not found")
        println("----------------------------")
        return
      }
    }


    /** ------------------ */
    /** Create output file */
    /** ------------------ */
    val outputFile = new File(outputFileName)

    val writerObj = new PrintWriter(outputFile)
    writerObj.close()



    /** --------------------------------- */
    /** Process transactions line by line */
    /** --------------------------------- */
    implicit val formats = DefaultFormats // for JSON parsing format

    var venmoGraphObj = new VenmoGraph()
    var lineNum = 0

    for (line <- Source.fromFile(inputFileName).getLines) {
        lineNum += 1
        venmoGraphObj.processTransaction(line, lineNum, outputFile)
    }


  }

}

